
package main;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CarServiceImplService", targetNamespace = "http://main/", wsdlLocation = "http://denisPc:8080/CarServer/CarServiceImplService?wsdl")
public class CarServiceImplService
    extends Service
{

    private final static URL CARSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CARSERVICEIMPLSERVICE_QNAME = new QName("http://main/", "CarServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://denisPc:8080/CarServer/CarServiceImplService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CARSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CarServiceImplService() {
        super(__getWsdlLocation(), CARSERVICEIMPLSERVICE_QNAME);
    }

    public CarServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARSERVICEIMPLSERVICE_QNAME, features);
    }

    public CarServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CARSERVICEIMPLSERVICE_QNAME);
    }

    public CarServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARSERVICEIMPLSERVICE_QNAME, features);
    }

    public CarServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CarServiceImpl
     */
    @WebEndpoint(name = "CarServiceImplPort")
    public CarServiceImpl getCarServiceImplPort() {
        return super.getPort(new QName("http://main/", "CarServiceImplPort"), CarServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarServiceImpl
     */
    @WebEndpoint(name = "CarServiceImplPort")
    public CarServiceImpl getCarServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://main/", "CarServiceImplPort"), CarServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CARSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CARSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
